# -*- mode: ruby -*-
# vi: set ft=ruby :
# online documentation at https://docs.vagrantup.com.
Vagrant.configure(2) do |config|  
  config.vm.box = "centos6.7"
  config.vm.synced_folder "/home", "/ext"

  config.vm.define :vm1 do |vm1|
    vm1.vm.hostname = "puppet.srv"
    vm1.vm.network :private_network, ip:"192.168.56.10"
    vm1.vm.provider :virtualbox do |vh1|
      vh1.name = "pupserver"
      vh1.customize ["modifyvm", :id, "--memory", 3072]
      vh1.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end 
  end 

  config.vm.define :vm2 do |vm2|
    vm2.vm.hostname = "puppet.agent"
    vm2.vm.network :private_network, ip:"192.168.56.11"
    vm2.vm.provider :virtualbox do |vh2|
      vh2.name = "pupagent"
      vh2.customize ["modifyvm", :id, "--memory", 2048]
      vh2.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end 
  end 
end # End Of Vagrand
